### ISSUE TITLE
Create a search input element with a search button

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#13]
Acceptance Criteria
The user can type on the search bar 
When he clicks on the search now button
The recipe API is triggered

Definition of Done
The user inputs a recipe and clicks search now, The user can see the query results on the console.

**Comment by JonRahman** [comment]
Michal will work on this throughout the holiday as well

**Comment by ikramismailx** [comment]
The length of the search input is too long, couldn't figure a way to reduce the size and fit it similar to wireframe.
