### ISSUE TITLE
Create recipe cards to be shown when the submit button is clicked on recipes page

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#22]
The user should be able to see the search results in the form of cards after he/she clicks the submit button. 

The recipe.js console logs recipes 

![image](https://github.com/noah-sheldon/nutriScript/assets/36855642/5cf430ba-8a72-42bb-bf23-0a7a9689ca8c)

Map this complex object into bootstrap cards and display.

Response JSON
[receipe_api_git.json](https://github.com/noah-sheldon/nutriScript/files/13773768/receipe_api_git.json)

**Comment by JonRahman** [comment]
Ive added and commited code for this. It doesnt seem to work so Ill continue on this.
