### ISSUE TITLE
Implement nutrition analsysis view in nutrition.js

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#29]
![image](https://github.com/noah-sheldon/nutriScript/assets/36855642/308b9646-54db-42e0-9be3-75af70f1d653)

There is no nutrition analysis done here!

Attaching JSON for implementing the correct view.

[nutrition_final_api.json](https://github.com/noah-sheldon/nutriScript/files/13802071/nutrition_final_api.json)

**Comment by jobmoonday** [comment]
I am working on it
