### ISSUE TITLE
Use this project presentation templateLinks to an external site. to address the following:

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#30]
[Project Presentation Template - MAKE A COPY! DO NOT REQUEST EDIT ACCESS.pptx](https://github.com/noah-sheldon/nutriScript/files/13802078/Project.Presentation.Template.-.MAKE.A.COPY.DO.NOT.REQUEST.EDIT.ACCESS.pptx)

![image](https://github.com/noah-sheldon/nutriScript/assets/36855642/d7645964-18bf-48d6-bb4a-a397f1bf11d6)

**Comment by ikramismailx** [comment]
challenged/issues we faced as a team - i am stuck on.
