### ISSUE TITLE
nutrition.js to use a POST request rather than GET request

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#32]
https://developer.edamam.com/edamam-docs-nutrition-api

![image](https://github.com/noah-sheldon/nutriScript/assets/36855642/33124b9d-ebda-4c1c-8e5a-18f718039bc6)

**Comment by jobmoonday** [comment]
I tried it but I couldn't manage. I have no idea how to send the post request; it requires JSON object in the request body. I have already planned and wrote my code according to GET request, which serves the purpose. If I switch to POST request now, I won't have enough time to finish my code on time.

**Comment by jobmoonday** [comment]
I am working on using POST instead of GET. I hope I can manage

**Comment by noah-sheldon** [comment]
https://github.com/noah-sheldon/nutriScript/issues/32

Check out this branch. I have solved it already. The POST request is working.
