### ISSUE TITLE
update readme to include screenshots

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#42]

**Comment by JonRahman** [comment]
ive created a pull request

**Comment by JonRahman** [comment]
![homepage](https://github.com/noah-sheldon/nutriScript/assets/145556007/7e8b88e3-765e-4771-8116-71cea0b1cef7)
![nutrition](https://github.com/noah-sheldon/nutriScript/assets/145556007/ab5fd883-6de3-4b6b-950a-50d5fb9d8e35)
![recipe](https://github.com/noah-sheldon/nutriScript/assets/145556007/ae7f89e9-755e-4b4c-b047-aba8eabbb0b2)
