### ISSUE TITLE
Hide background images for mobile screen sizes

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#43]

**Comment by JonRahman** [comment]
@media (max-width: 768px) {
    #textBox {
        width: 90%;
        background-color: rgba(255, 255, 255, 0.7);
        color: black;
    }
}

**Comment by JonRahman** [comment]
line 67 in the html 

<p id="textBox">Explore a recipe database containing over 2.3 million recipes with comprehensive nutrition analysis
                    for
                    each recipe! </p>

**Comment by JonRahman** [comment]
<p id="textBox">Explore a recipe database containing over 2.3 million recipes with comprehensive nutrition analysis
                    for
                    each recipe! </p>

**Comment by JonRahman** [comment]
<p id="textBox"

**Comment by JonRahman** [comment]
add textBox id to index.html line 67
