### ISSUE TITLE
Create layout using HTML, CSS and Bootstrap

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#6]
Acceptance Criteria:

Create a layout using BootStrap HTML and CSS
The UI is responsive
The layouts follow the wireframe
Best naming practices are followed(classes and ids)

Definition of Done:
The screen adapts to different sizes
The layout is a replica of the wireframe

**Comment by ikramismailx** [comment]
Sidebar on the web, moves as you scroll. A solution to keep it in place throughout I may need help with.
