### ISSUE TITLE
Bootstrap cards for recipe viewing uswing HTML CSS and bootstrap

### ISSUE THREAD

**Issue by noah-sheldon** [noah-sheldon/nutriScript#9]
![Image](https://github.com/noah-sheldon/nutriScript/assets/36855642/2f28d7b6-8fb9-49f8-915f-1e6e5da7acc0)

Use the json response from recipe API
Acceptance Criteria:
After the user clicks on a search
Create a recipe view for the users to view the recipes 

Definition of Done:

The recipe view structure is created using html,Css and Bootstrap

**Comment by noah-sheldon** [comment]
Adding JSON objects

[nutrition_api.json](https://github.com/noah-sheldon/nutriScript/files/13746045/nutrition_api.json)
[recipe_api_object.json](https://github.com/noah-sheldon/nutriScript/files/13746046/recipe_api_object.json)

**Comment by JonRahman** [comment]
cards have been created and i have sent it over to ikram to merge into her html for testing
